global:
  system: ironwood
  warmup_tries: 2
  num_runs: 5
  dtype: bfloat16
  xprof_timing: true
benchmarks:
- mesh_shape: 4x2x2
  name: reduce_scatter
  sweep:
    matrix_dim: [512, 1024, 2048]
  sharding_strategy: 4x2x2
