benchmark:
  # Sweep over different sizes for gemm_generalized
  name: gemm_generalized
  xprof_timing: true
  params:
    warmup_tries: 2
    num_runs: 5
    in_dtype: "bfloat16"
    out_dtype: "bfloat16"
    k: 2048
    n: 2048
  sweep:
    m:
      start: 1024
      end: 4096
      multiplier: 2
