benchmark:
  name: gemm_generalized
  xprof_timing: true
  params:
    warmup_tries: 2
    num_runs: 5
    in_dtype: bfloat16
    out_dtype: bfloat16
  cases:
    - m: 4096
      k: 4096
      n: 4096
    - m: 8192
      k: 8192
      n: 8192
