apiVersion: kueue.x-k8s.io/v1beta2
kind: ResourceFlavor
metadata:
  name: "flavor-tpu7x"
spec:
  nodeLabels:
    cloud.google.com/gke-tpu-accelerator: tpu7x
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: ClusterQueue
metadata:
  name: cluster-queue-tpu7x
spec:
  flavorFungibility:
    whenCanBorrow: MayStopSearch
    whenCanPreempt: TryNextFlavor
  namespaceSelector: {}
  preemption:
    borrowWithinCohort:
      policy: Never
    reclaimWithinCohort: Never
    withinClusterQueue: LowerPriority
  queueingStrategy: BestEffortFIFO
  resourceGroups:
  - coveredResources:
    - google.com/tpu
    flavors:
    - name: flavor-tpu7x
      resources:
      - name: google.com/tpu
        nominalQuota: 128
  stopPolicy: None
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: default
  name: "user-queue-tpu7x"
spec:
  clusterQueue: "cluster-queue-tpu7x"