system: ghostlite # TODO - b/544761589: Add support for ghostlite in systems.py

benchmark:
  name: all_gather
  warmup_tries: 2
  num_runs: 5
  dtype: bfloat16
  xprof_timing: false
  mesh_shape: 4x4
  sharding_strategy: 4x4
  sweep:
    matrix_dim: [512, 1024, 2048]
