benchmarks:
- benchmark_name: "gemm_throttling"
  trace_dir: "/home/amylin_google_com/traces/v6e_all_devices_trace"
  csv_path: "/home/amylin_google_com/traces/v6e_all_devices_trace"
  xlml_metrics_dir: "/home/amylin_google_com/traces/v6e_all_devices_trace"
  benchmark_sweep_params:
  - {m: 16384, k: 16384, n: 16384, num_runs: 1000, dtype: 'bfloat16', gap_strategy: 'data_gen_once_noblock_stressed_no_sharding'}
