benchmarks:
- benchmark_name: "gemm_throttling"
  trace_dir: "/tmp/ninja_v7x_unroll_trace"
  csv_path: "/tmp/ninja_v7x_unroll_trace"
  xlml_metrics_dir: "/tmp/ninja_v7x_unroll_trace"
  xla_dump_dir: "/tmp/ninja_v7x_unroll_trace/hlo_graphs"
  benchmark_sweep_params:
  - {m: 16384, k: 16384, n: 16384, num_runs: 100, dtype: 'bfloat16', gap_strategy: 'data_gen_once_unroll_loop'}
