system: ghostlite

benchmark:
  name: all_gather
  warmup_tries: 2
  num_runs: 5
  dtype: bfloat16
  xprof_timing: true
  mesh_shape: 2x4
  sharding_strategy: 2x4
  sweep:
    matrix_dim:
      start: 8
      end: 524288
      multiplier: 2
