benchmarks:
- benchmark_name: ppermute
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 1024, end: 5000, increase_by: 1024}, dtype: "bfloat16", dcn_size_range: 4, ici_size_range: 256}
  csv_path: "/tmp/microbenchmarks/collectives/ppermute_1024_to_5000"
  warmup_tries: 500
  tries: 10000
- benchmark_name: ppermute
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 5120, end: 20000, increase_by: 1024}, dtype: "bfloat16", dcn_size_range: 4, ici_size_range: 256}
  csv_path: "/tmp/microbenchmarks/collectives/ppermute_5120_to_20000"
  warmup_tries: 250
  tries: 1000
- benchmark_name: all_gather
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 1024, end: 5000, increase_by: 1024}, dtype: "bfloat16", dcn_size_range: 4, ici_size_range: 256}
  csv_path: "/tmp/microbenchmarks/collectives/all_gather_1024_to_5000"
  warmup_tries: 500
  tries: 10000
- benchmark_name: psum
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 1024, end: 5000, increase_by: 1024}, dtype: "bfloat16", dcn_size_range: 4, ici_size_range: 256}
  csv_path: "/tmp/microbenchmarks/collectives/psum_1024_to_5000"
  warmup_tries: 500
  tries: 10000
- benchmark_name: psum
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 5120, end: 20000, increase_by: 1024}, dtype: "bfloat16", dcn_size_range: 4, ici_size_range: 256}
  csv_path: "/tmp/microbenchmarks/collectives/psum_5120_to_20000"
  warmup_tries: 250
  tries: 1000
- benchmark_name: psum_scatter
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 1024, end: 5000, increase_by: 1024}, dtype: "bfloat16", dcn_size_range: 4, ici_size_range: 256}
  csv_path: "/tmp/microbenchmarks/collectives/psum_scatter_1024_to_5000"
  warmup_tries: 500
  tries: 10000
- benchmark_name: psum_scatter
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 5120, end: 20000, increase_by: 1024}, dtype: "bfloat16", dcn_size_range: 4, ici_size_range: 256}
  csv_path: "/tmp/microbenchmarks/collectives/psum_scatter_5120_to_20000"
  warmup_tries: 250
  tries: 1000
- benchmark_name: all_to_all
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 1024, end: 5000, increase_by: 1024}, dtype: "bfloat16", dcn_size_range: 4, ici_size_range: 256}
  csv_path: "/tmp/microbenchmarks/collectives/all_to_all_1024_to_5000"
  warmup_tries: 500
  tries: 10000
- benchmark_name: all_to_all
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 5120, end: 20000, increase_by: 1024}, dtype: "bfloat16", dcn_size_range: 4, ici_size_range: 256}
  csv_path: "/tmp/microbenchmarks/collectives/all_to_all_5120_to_20000"
  warmup_tries: 250
  tries: 1000