benchmarks:
- benchmark_name: all_gather
  benchmark_sweep_params:
  - {matrix_dim: 4, dtype: "bfloat16", dcn_size_range: 1, ici_size_range: 4}
- benchmark_name: all_to_all
  benchmark_sweep_params:
  - {matrix_dim_range: 4, dtype: "bfloat16", dcn_size_range: 1, ici_size_range: 4}
