benchmarks:
- benchmark_name: "numpy_convolve"
  benchmark_sweep_params:
  - {input_size_range: {start: 256, end: 512, multiplier: 2}, kernel_size: 3, padding_mode: "same"}
  - {input_size: 2048, kernel_size_range: {start: 3, end: 128, multiplier: 2}, padding_mode: "valid"}
  - {input_size: 2048, kernel_size: 127, padding_mode: "full"}
  xlml_metrics_dir: "/tmp/microbenchmarks/convolution"
- benchmark_name: "scipy_signal_convolve"
  benchmark_sweep_params:
  - {input_size_range: {start: 256, end: 1024, multiplier: 2}, kernel_size: 3, dimension: 2, padding_mode: "same"}
  - {input_size: 128, kernel_size: 3, dimension: 3, padding_mode: "valid"}
  xlml_metrics_dir: "/tmp/microbenchmarks/convolution"
- benchmark_name: "scipy_signal_convolve2d"
  benchmark_sweep_params:
  - {input_size_range: {start: 256, end: 512, multiplier: 2}, kernel_size: 3, padding_mode: "valid"}
  - {input_size: 1024, kernel_size: 63, padding_mode: "valid"}
  - {input_size: 1024, kernel_size: 127, padding_mode: "valid"}
  xlml_metrics_dir: "/tmp/microbenchmarks/convolution"
- benchmark_name: "lax_conv_general_dilated"
  benchmark_sweep_params:
  - {batch_size_range: {start: 16, end: 32, multiplier: 2}, input_h: 1024, input_w: 1024, kernel_h: 255, kernel_w: 255, in_channel: 16, out_channel: 16, padding_mode: "valid", stride: 1, dilation: 1, dtype: "bfloat16"}
  - {batch_size_range: 16, input_h: 128, input_w: 128, kernel_h: 63, kernel_w: 63, in_channel: 16, out_channel: 16, padding_mode: "valid", stride: 1, dilation: 1, dtype: "bfloat16"}
  csv_path: "/tmp/microbenchmarks/convolution"
  xlml_metrics_dir: "/tmp/microbenchmarks/convolution"
