benchmarks:
- benchmark_name: ppermute
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 16, end: 65536, multiplier: 2}, dtype: "bfloat16", dcn_size_range: 1, ici_size_range: 16, num_runs: 100}
  xlml_metrics_dir: "/tmp/microbenchmarks/outputs"
  trace_dir: "/tmp/microbenchmarks/outputs"
  csv_path: "/tmp/microbenchmarks/outputs"
