benchmarks:
- benchmark_name: all_gather
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 8192, end: 32768, multiplier: 2}, dtype: "bfloat16", dcn_size_range: 1, ici_size_range: 256, num_runs: 20}
  xlml_metrics_dir: "/tmp/microbenchmarks/outputs"
  csv_path: "/tmp/microbenchmarks/outputs"
  trace_dir: "/tmp/microbenchmarks/outputs"
- benchmark_name: psum_scatter
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 8192, end: 32768, multiplier: 2}, dtype: "bfloat16", dcn_size_range: 1, ici_size_range: 256, num_runs: 20}
  xlml_metrics_dir: "/tmp/microbenchmarks/outputs"
  csv_path: "/tmp/microbenchmarks/outputs"
  trace_dir: "/tmp/microbenchmarks/outputs"
- benchmark_name: psum
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 8192, end: 32768, multiplier: 2}, dtype: "bfloat16", dcn_size_range: 1, ici_size_range: 256, num_runs: 20}
  xlml_metrics_dir: "/tmp/microbenchmarks/outputs"
  csv_path: "/tmp/microbenchmarks/outputs"
  trace_dir: "/tmp/microbenchmarks/outputs"
