system: ironwood

benchmark:
  name: gemm_generalized
  warmup_tries: 2
  num_runs: 5
  dtype: bfloat16
  xprof_timing: true
  cases:
    - m: 4096
      k: 4096
      n: 4096
    - m: 8192
      k: 8192
      n: 8192
