apiVersion: batch/v1
kind: Job
metadata:
  name: job-waiter
spec:
  template:
    spec:
      containers:
      - name: main-app
        image: python:3.12
        command:
        - bash
        - -c
        - |
          set -ex
          git clone https://github.com/AI-Hypercomputer/accelerator-microbenchmarks.git
          cd accelerator-microbenchmarks
          git checkout tpu7x-auto

          GCS_BUCKET_DIR=${GCS_PATH}
          python Ironwood/guides/automation/aggregator.py --bucket_path=${GCS_BUCKET_DIR}
          sleep infinity
      restartPolicy: Never
