apiVersion: batch/v1
kind: Job
metadata:
  name: job-waiter
spec:
  template:
    spec:
      containers:
      - name: main-app
        image: ubuntu
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Collectives job is finally done."
          echo "Everything is all fine!"
      restartPolicy: Never