apiVersion: kueue.x-k8s.io/v1beta2
kind: ResourceFlavor
metadata:
  name: "flavor-${TOPOLOGY}"
spec:
  nodeLabels:
    cloud.google.com/gke-tpu-accelerator: tpu7x
    cloud.google.com/gke-tpu-topology: ${TOPOLOGY}
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: ClusterQueue
metadata:
  name: cluster-queue-${TOPOLOGY}
spec:
  flavorFungibility:
    whenCanBorrow: MayStopSearch
    whenCanPreempt: TryNextFlavor
  namespaceSelector: {}
  preemption:
    borrowWithinCohort:
      policy: Never
    reclaimWithinCohort: Never
    withinClusterQueue: LowerPriority
  queueingStrategy: BestEffortFIFO
  resourceGroups:
  - coveredResources:
    - google.com/tpu
    flavors:
    - name: flavor-${TOPOLOGY}
      resources:
      - name: google.com/tpu
        nominalQuota: ${TPUS}
  stopPolicy: None
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: default
  name: "user-queue-${TOPOLOGY}"
spec:
  clusterQueue: "cluster-queue-${TOPOLOGY}"